using Microsoft.Xna.Framework;
using System.Collections.Generic;
using System.IO;
using Terraria;
using Terraria.DataStructures;
using Terraria.GameInput;
using Terraria.ModLoader;
using Terraria.ModLoader.IO;

namespace ModularEffectLib.Core.EventSystem
{
    internal static class Delegates
    {
        #region ModPlayer
        internal delegate bool CanBeHitByNPC(Player me, NPC npc, ref int cooldownSlot, Item effectOwner);
        internal delegate bool CanBeHitByProjectile(Player me, Projectile proj, Item effectOwner);
        internal delegate bool CanBuyItem(Player me, NPC vendor, Item[] shopInventory, Item item, Item effectOwner);
        internal delegate bool CanHitPvp(Player me, Item item, Player target, Item effectOwner);
        internal delegate bool CanHitPvpWithProj(Player me, Projectile proj, Player target, Item effectOwner);
        internal delegate bool CanSellItem(Player me, NPC vendor, Item[] shopInventory, Item item, Item effectOwner);
        internal delegate bool ConsumeAmmo(Player me, Item weapon, Item ammo, Item effectOwner);
        internal delegate bool ModifyNurseHeal(Player me, NPC nurse, ref int health, ref bool removeDebuffs, ref string chatText, Item effectOwner);
        internal delegate bool PreHurt(Player me, bool pvp, bool quiet, ref int damage, ref int hitDirection, ref bool crit, ref bool customDamage, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource, Item effectOwner);
        internal delegate bool PreItemCheck(Player me, Item effectOwner);
        internal delegate bool PreKill(Player me, double damage, int hitDirection, bool pvp, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource, Item effectOwner);
        internal delegate bool ShiftClickSlot(Player me, Item[] inventory, int context, int slot, Item effectOwner);
        internal delegate bool Shoot(Player me, Item item, ref Vector2 position, ref float speedX, ref float speedY, ref int type, ref int damage, ref float knockBack, Item effectOwner);
        internal delegate bool? CanHitNPC(Player me, Item item, NPC target, Item effectOwner);
        internal delegate bool? CanHitNPCWithProj(Player me, Projectile proj, NPC target, Item effectOwner);
        internal delegate float MeleeSpeedMultiplier(Player me, Item item, Item effectOwner);
        internal delegate float UseTimeMultiplier(Player me, Item item, Item effectOwner);
        internal delegate TagCompound Save(Player me, Item effectOwner);
        internal delegate void AnglerQuestReward(Player me, float rareMultiplier, List<Item> rewardItems, Item effectOwner);
        internal delegate void CatchFish(Player me, Item fishingRod, Item bait, int power, int liquidType, int poolSize, int worldLayer, int questFish, ref int caughtType, ref bool junk, Item effectOwner);
        internal delegate void clientClone(Player me, ModPlayer clientClone, Item effectOwner);
        internal delegate void DrawEffects(Player me, PlayerDrawInfo drawInfo, ref float r, ref float g, ref float b, ref float a, ref bool fullBright, Item effectOwner);
        internal delegate void FrameEffects(Player me, Item effectOwner);
        internal delegate void GetDyeTraderReward(Player me, List<int> rewardPool, Item effectOwner);
        internal delegate void GetFishingLevel(Player me, Item fishingRod, Item bait, ref int fishingLevel, Item effectOwner);
        internal delegate void GetHealLife(Player me, Item item, bool quickHeal, ref int healValue, Item effectOwner);
        internal delegate void GetHealMana(Player me, Item item, bool quickHeal, ref int healValue, Item effectOwner);
        internal delegate void GetWeaponCrit(Player me, Item item, ref int crit, Item effectOwner);
        internal delegate void GetWeaponKnockback(Player me, Item item, ref float knockback, Item effectOwner);
        internal delegate void Hurt(Player me, bool pvp, bool quiet, double damage, int hitDirection, bool crit, Item effectOwner);
        internal delegate void Initialize(Player me, Item effectOwner);
        internal delegate void Kill(Player me, double damage, int hitDirection, bool pvp, PlayerDeathReason damageSource, Item effectOwner);
        internal delegate void Load(Player me, TagCompound tag, Item effectOwner);
        internal delegate void LoadLegacy(Player me, BinaryReader reader, Item effectOwner);
        internal delegate void MeleeEffects(Player me, Item item, Rectangle hitbox, Item effectOwner);
        internal delegate void ModifyDrawHeadLayers(Player me, List<PlayerHeadLayer> layers, Item effectOwner);
        internal delegate void ModifyDrawInfo(Player me, ref PlayerDrawInfo drawInfo, Item effectOwner);
        internal delegate void ModifyDrawLayers(Player me, List<PlayerLayer> layers, Item effectOwner);
        internal delegate void ModifyHitByNPC(Player me, NPC npc, ref int damage, ref bool crit, Item effectOwner);
        internal delegate void ModifyHitByProjectile(Player me, Projectile proj, ref int damage, ref bool crit, Item effectOwner);
        internal delegate void ModifyHitNPC(Player me, Item item, NPC target, ref int damage, ref float knockback, ref bool crit, Item effectOwner);
        internal delegate void ModifyHitNPCWithProj(Player me, Projectile proj, NPC target, ref int damage, ref float knockback, ref bool crit, ref int hitDirection, Item effectOwner);
        internal delegate void ModifyHitPvp(Player me, Item item, Player target, ref int damage, ref bool crit, Item effectOwner);
        internal delegate void ModifyHitPvpWithProj(Player me, Projectile proj, Player target, ref int damage, ref bool crit, Item effectOwner);
        internal delegate void ModifyManaCost(Player me, Item item, ref float reduce, ref float mult, Item effectOwner);
        internal delegate void ModifyNursePrice(Player me, NPC nurse, int health, bool removeDebuffs, ref int price, Item effectOwner);
        internal delegate void ModifyScreenPosition(Player me, Item effectOwner);
        internal delegate void ModifyWeaponDamage(Player me, Item item, ref float add, ref float mult, ref float flat, Item effectOwner);
        internal delegate void ModifyZoom(Player me, ref float zoom, Item effectOwner);
        internal delegate void NaturalLifeRegen(Player me, ref float regen, Item effectOwner);
        internal delegate void OnConsumeAmmo(Player me, Item weapon, Item ammo, Item effectOwner);
        internal delegate void OnConsumeMana(Player me, Item item, int manaConsumed, Item effectOwner);
        internal delegate void OnEnterWorld(Player me, Player player, Item effectOwner);
        internal delegate void OnHitAnything(Player me, float x, float y, Entity victim, Item effectOwner);
        internal delegate void OnHitByNPC(Player me, NPC npc, int damage, bool crit, Item effectOwner);
        internal delegate void OnHitByProjectile(Player me, Projectile proj, int damage, bool crit, Item effectOwner);
        internal delegate void OnHitNPC(Player me, Item item, NPC target, int damage, float knockback, bool crit, Item effectOwner);
        internal delegate void OnHitNPCWithProj(Player me, Projectile proj, NPC target, int damage, float knockback, bool crit, Item effectOwner);
        internal delegate void OnHitPvp(Player me, Item item, Player target, int damage, bool crit, Item effectOwner);
        internal delegate void OnHitPvpWithProj(Player me, Projectile proj, Player target, int damage, bool crit, Item effectOwner);
        internal delegate void OnMissingMana(Player me, Item item, int neededMana, Item effectOwner);
        internal delegate void OnRespawn(Player me, Player player, Item effectOwner);
        internal delegate void PlayerConnect(Player me, Player player, Item effectOwner);
        internal delegate void PlayerDisconnect(Player me, Player player, Item effectOwner);
        internal delegate void PostBuyItem(Player me, NPC vendor, Item[] shopInventory, Item item, Item effectOwner);
        internal delegate void PostHurt(Player me, bool pvp, bool quiet, double damage, int hitDirection, bool crit, Item effectOwner);
        internal delegate void PostItemCheck(Player me, Item effectOwner);
        internal delegate void PostNurseHeal(Player me, NPC nurse, int health, bool removeDebuffs, int price, Item effectOwner);
        internal delegate void PostSavePlayer(Player me, Item effectOwner);
        internal delegate void PostSellItem(Player me, NPC vendor, Item[] shopInventory, Item item, Item effectOwner);
        internal delegate void PostUpdate(Player me, Item effectOwner);
        internal delegate void PostUpdateBuffs(Player me, Item effectOwner);
        internal delegate void PostUpdateEquips(Player me, Item effectOwner);
        internal delegate void PostUpdateMiscEffects(Player me, Item effectOwner);
        internal delegate void PostUpdateRunSpeeds(Player me, Item effectOwner);
        internal delegate void PreSaveCustomData(Player me, Item effectOwner);
        internal delegate void PreSavePlayer(Player me, Item effectOwner);
        internal delegate void PreUpdate(Player me, Item effectOwner);
        internal delegate void PreUpdateBuffs(Player me, Item effectOwner);
        internal delegate void PreUpdateMovement(Player me, Item effectOwner);
        internal delegate void ProcessTriggers(Player me, TriggersSet triggersSet, Item effectOwner);
        internal delegate void ResetEffects(Player me, Item effectOwner);
        internal delegate void SendClientChanges(Player me, ModPlayer clientPlayer, Item effectOwner);
        internal delegate void SetControls(Player me, Item effectOwner);
        internal delegate void SetupStartInventory(Player me, IList<Item> items, bool mediumcoreDeath, Item effectOwner);
        internal delegate void SyncPlayer(Player me, int toWho, int fromWho, bool newPlayer, Item effectOwner);
        internal delegate void UpdateAutopause(Player me, Item effectOwner);
        internal delegate void UpdateBadLifeRegen(Player me, Item effectOwner);
        internal delegate void UpdateBiomes(Player me, Item effectOwner);
        internal delegate void UpdateBiomeVisuals(Player me, Item effectOwner);
        internal delegate void UpdateDead(Player me, Item effectOwner);
        internal delegate void UpdateEquips(Player me, ref bool wallSpeedBuff, ref bool tileSpeedBuff, ref bool tileRangeBuff, Item effectOwner);
        internal delegate void UpdateLifeRegen(Player me, Item effectOwner);
        internal delegate void UpdateVanityAccessories(Player me, Item effectOwner);
        #endregion
    }
}
